import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Ficha200 } from '../compartido/interfaces/ficha-200';

@Injectable({
  providedIn: 'root'
})
export class Ficha200Service {
  dataEjemplo: Ficha200[] = [
    {
      "Tipo_Documento": "DNI",
      "Nro_Documento": "77609058",
      "Nombres": "LUANA MARGARET YHORLEY",
      "Apellido_Paterno": "ROJAS",
      "Apellido_Materno": "MARIN",
      "Celular": "952244705",
      "Telefono": "952447054",
      "Edad": "9",
      "domicilio_residencia": "INFORMACION DE DOMICILIO",
      "Direccion": "Avenida Túpac Amaru, Celendín, Cajamarca, 06226, PER",
      "Departamento": "Cajamarca",
      "Provincia": "Celendín",
      "Distrito": "Celendín",
      "Latitud": "-6.8665408",
      "Longitud": "-78.1426736",
      "Personal_Salud": "NO",
      "Comun_profesion": "",
      "Tiene_Sintomas": "NO",
      "Fecha_Inicio_Sintomas": "",
      "Sintomas_Presenta": "",
      "Tos": "0",
      "Dolor_Garganta": "0",
      "Congestion_Nasal": "0",
      "Dificultad_Respiratoria": "0",
      "Fiebre_Escalofrio": "0",
      "Malestar_General": "0",
      "Diarrea": "0",
      "Nauseas_Vomito": "0",
      "Presenta_Cefalea": "0",
      "Irritabilidad_Confusion": "0",
      "Presenta_Dolor": "0",
      "Presenta_Otros": "0",
      "Dolor_Presenta": "",
      "Dolor_Presenta_Muscular": "0",
      "Dolor_Presenta_Abdominal": "0",
      "Dolor_Presenta_Pecho": "0",
      "Dolor_Presenta_Articulaciones": "0",
      "Dolor_Presenta_Otros": "",
      "Ficha_200_28_fecha_notificacion": "2020-05-26",
      "Ficha_200_29_numero_dni_personal_llena_ficha": "42453205",
      "Ficha_200_30_nombres_apellidos_personal_llena_ficha": "JOSE CAMILO VASQUEZ ZAFRA",
      "Ficha_200_31_fecha_nacimiento_paciente": "1984-03-28",
      "Ficha_200_32_edad": "9",
      "Ficha_200_33_sexo_biologico": "MASCULINO",
      "Ficha_200_34_tipo_seguro": "SIS",
      "Ficha_200_35_ingrese_tipo_seguro": "",
      "Ficha_200_36_correo": "",
      "Ficha_200_37_profesion_ocupacion": "ESTUDIANTE",
      "Ficha_200_tomaron_prueba_rapida": "NO",
      "Ficha_200_resultado_prueba_rapida": "no_reactivo",
      "Ficha_200_fecha_prueba_rapida": "2020-05-26",
      "Ficha_200_resultado_segunda_prueba_rapida": "",
      "Ficha_200_38_hospitalizado": "NO",
      "Ficha_200_39_fecha_hospitalizacion": "",
      "Ficha_200_40_tiene_algun_signo": "NO",
      "Ficha_200_41_temeratura_paciente": "36.8",
      "Ficha_200_42_marque_signos_presenta": "",
      "Ficha_200_42_marque_signos_presenta_exudadoFaringeo": "0",
      "Ficha_200_42_marque_signos_presenta_inteccionConjuntival": "0",
      "Ficha_200_42_marque_signos_presenta_convulsion": "0",
      "Ficha_200_42_marque_signos_presenta_coma": "0",
      "Ficha_200_42_marque_signos_presenta_disnea_taquipnea": "0",
      "Ficha_200_42_marque_signos_presenta_otros": "0",
      "Ficha_200_otros_especificar": "0",
      "Ficha_200_43_condiciones_comorbilidad": "",
      "Ficha_200_43_condiciones_comorbilidad_embarazo_puerperio": "0",
      "Ficha_200_43_condiciones_comorbilidad_comorbilidad_cardiovascula": "0",
      "Ficha_200_43_condiciones_comorbilidad_diabetes": "0",
      "Ficha_200_43_condiciones_comorbilidad_enfermedadHepatica": "",
      "Ficha_200_43_condiciones_comorbilidad_enfCronicaNeurologica": "",
      "Ficha_200_43_condiciones_comorbilidad_posparto_6semanas": "",
      "Ficha_200_43_condiciones_comorbilidad_inmunodeficiencia_vih": "",
      "Ficha_200_43_condiciones_comorbilidad_enfRenal": "",
      "Ficha_200_43_condiciones_comorbilidad_danoHepatico": "",
      "Ficha_200_43_condiciones_comorbilidad_enfPulmonarCronica": "0",
      "Ficha_200_43_condiciones_comorbilidad_cancer": "0",
      "Ficha_200_43_condiciones_comorbilidad_otros": "0",
      "Ficha_200_43_condiciones_comorbilidad_mayor60anios": "0",
      "Ficha_200_43_condiciones_comorbilidad_hipertensionArterial": "0",
      "Ficha_200_43_condiciones_comorbilidad_obesidad": "0",
      "Ficha_200_43_condiciones_comorbilidad_asma": "0",
      "Ficha_200_43_condiciones_comorbilidad_insRenalCronica": "0",
      "Ficha_200_43_condiciones_comorbilidad_enf_tratInmunos": "0",
      "Ficha_200_embarazo_trimestre": "",
      "Ficha_200_otros_especificar_2": "0",
      "Ficha_200_44_antecedente_viaje_14_diasfi_sintomas": "SI",
      "Ficha_200_pais": "PERU",
      "Ficha_200_ciudad": "lima",
      "Ficha_200_pais1": "",
      "Ficha_200_ciudad1": "",
      "Ficha_200_pais2": "",
      "Ficha_200_ciudad2": "",
      "Ficha_200_45_contacto_caso_confirmado_probable_14diasfi_sintomas": "no",
      "Ficha_200_46_fecha_obtencion_muestra": "2020-05-26",
      "Ficha_200_47_obtencion_muestra_rt_pcr": "",
      "Ficha_200_47_obtencion_muestra_rt_pcr_hisopado_nasalfaringeo": "",
      "Ficha_200_47_obtencion_muestra_rt_pcr_aspirado_traqueal": "",
      "Ficha_200_47_obtencion_muestra_rt_pcr_aspirado_broncoalve": "",
      "Ficha_200_47_obtencion_muestra_rt_pcr_lavado_broncoalve": "",
      "Ficha_200_47_obtencion_muestra_rt_pcr_tejido_pulmonar": "",
      "Ficha_200_48_numero_contactos_consignar": "",
      "Ficha_200_apellidos_nombres_01": "",
      "Ficha_200_numero_dni_01": "",
      "Ficha_200_numero_celular_01": "",
      "Ficha_200_factores_riesgo_01": "",
      "Ficha_200_factores_riesgo_asma_01": "",
      "Ficha_200_factores_riesgo_enf_PulmonarCronica_01": "",
      "Ficha_200_factores_riesgo_ins_Renal_Cronica_01": "",
      "Ficha_200_factores_riesgo_obesidad_01": "",
      "Ficha_200_factores_riesgo_personalSalud_01": "",
      "Ficha_200_factores_riesgo_enfCardiovasculares_01": "",
      "Ficha_200_factores_riesgo_Diabetes_01": "",
      "Ficha_200_factores_riesgo_enf_tratamiento_Inmuno_01": "",
      "Ficha_200_factores_riesgo_hipertensionArterial_01": "",
      "Ficha_200_factores_riesgo_mayor60anios_01": "",
      "Ficha_200_factores_riesgo_tuberculosis_01": "",
      "Ficha_200_factores_riesgo_cancer_01": "",
      "Ficha_200_factores_riesgo_embarazo_puerperio_01": "",
      "Ficha_200_parentesco_01": "",
      "Ficha_200_observacion_ficha_200": "",
      "Ficha_200_procedera_llenar_ficha_seguimiento": "",
      "Ficha_Resultado_prueba_rapida": "no_reactivo",
      "Ficha_fecha_prueba_rapida": "2020-05-26",
      "Comun_documento_paciente": "77609058",
      "Ficha_dni_registrador": "42453205",
      "Ficha_nombres_apellidos_registrador": "VASQUEZ ZAFRA",
      "Procedencia_Resultado_prueba_rapida": "FICHA 100 - 1RA PRUEBA",
      "fecha_registro": "2020-07-14",
      "id_ubigeo": "060301",
      "cod_establecimiento": ""
    }

  ]


  constructor(private http: HttpClient) { }
  devolverFicha200(TIPO_DOC: string, NRO_DOC: String) {

    return this.dataEjemplo
  }

}
