export class PruebaDiagnostico {
    public Tipo_Documento? : string
    public Nro_Documento? : string
    public nombres? : string
    public Apellido_Paterno? : string
    public Apellido_Materno? : string
    public comun_sexo_paciente? : string
    public Celular? : string
    public Teléfono? : string
    public Edad? : string
    public domicilio_residencia? : string
    public Direccion? : string
    public Departamento? : string
    public Provincia? : string
    public Distrito? : string
    public Latitud? : string
    public Longitud? : string
    public Personal_Salud? : string
    public Comun_profesion? : string
    public Tiene_Sintomas? : string
    public Fecha_Inicio_Sintomas_de_la_Ficha_Paciente? : string
    public Sintomas_Presenta? : string
    public Tos? : string
    public Dolor_Garganta? : string
    public Congestion_Nasal? : string
    public Dificultad_Respiratoria? : string
    public Fiebre_Escalofrio? : string
    public Malestar_General? : string
    public Diarrea? : string
    public Nauseas_Vomito? : string
    public Presenta_Cefalea? : string
    public Irritabilidad_Confusion? : string
    public Presenta_Dolor? : string
    public Presenta_Otros? : string
    public Dolor_Presenta? : string
    public Dolor_Presenta_Muscular? : string
    public Dolor_Presenta_Abdominal? : string
    public Dolor_Presenta_Pecho? : string
    public Dolor_Presenta_Articulaciones? : string
    public Dolor_Presenta_Otros? : string
    public Tipo_de_Prueba? : string
    public Tipo_de_Muestra? : string
    public Tipo_de_Lectura? : string
    public Fecha_Ejecucion_Prueba? : string
    public Procedencia_Solicitud_Diagnostico? : string
    public Resultado? : string
    public Fotografia_Prueba? : string
    public Resultado_Segunda_Prueba? : string
    public Valor_Obtenido? : string
    public Unidad? : string
    public Fotografia_Segunda_Prueba? : string
    public Clasificacion_Clinica_Severidad? : string
    public Fecha_de_Inicio_de_Síntomas_de_la_Prueba? : string
    public Riesgo? : string
    public Riesgo_Personal_Salud? : string
    public Riesgo_Obesidad? : string
    public Riesgo_Enf_Pulmonar_Cronica? : string
    public Riesgo_Diabetes? : string
    public Riesgo_Hipertension_Arterial? : string
    public Riesgo_Enf_Tratinmuno? : string
    public Riesgo_Cancer? : string
    public Riesgo_Embarazo? : string
    public Riesgo_Mayor_60_Años? : string
    public Riesgo_Ninguna? : string
    public Riesgo_Enf_Cardiovascular? : string
    public Riesgo_Asma? : string
    public Riesgo_Renal_Cronica? : string
    public Registrador? : string
    public Doc_Registrador? : string
    public Geresa_Diresa_Diris? : string
    public Hospital_Instituto_Otros? : string
    public Aplicara_PCR? : string
    public Observacion? : string
    public Id_Registro? : string
    public Resultado1? : string
    public Fecha_Prueba? : string
    public Usuario_Kobo? : string
    public Usuario? : string
    public Nombres_Usuario? : string
    public Apellidos_Usuario? : string
    public Correo_Usuario? : string
    public nom_reniec? : string
    public apep_reniec? : string
    public apem_reniec? : string
    public sexo_reniec? : string
    public fecha_nac_reniec? : string
    public dir_reniec? : string
    public dep_reniec? : string
    public prov_reniec? : string
    public dist_reniec? : string
    public ubigeo_reniec? : string
    public fecha_registro? : string
    public TipoConglomerado? : string
    public Conglomerado? : string
    public id_ubigeo? : string
    public cod_establecimiento? : string
    public Etnia? : string

}